//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.108;Initial Catalog=projectinformation;User ID=sa;Password=" +
            "sa")]
        public string projectinformationConnectionString {
            get {
                return ((string)(this["projectinformationConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.108;Initial Catalog=ProjectInformation;User ID=sa;Password=" +
            "sa")]
        public string ProjectInformationConnectionString1 {
            get {
                return ((string)(this["ProjectInformationConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.108;Initial Catalog=ProjectInformation;User ID=sa")]
        public string ProjectInformationConnectionString2 {
            get {
                return ((string)(this["ProjectInformationConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString3 {
            get {
                return ((string)(this["ProjectInformationConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString4 {
            get {
                return ((string)(this["ProjectInformationConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString5 {
            get {
                return ((string)(this["ProjectInformationConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString6 {
            get {
                return ((string)(this["ProjectInformationConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString7 {
            get {
                return ((string)(this["ProjectInformationConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString8 {
            get {
                return ((string)(this["ProjectInformationConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectInformation;User ID=sa")]
        public string ProjectInformationConnectionString9 {
            get {
                return ((string)(this["ProjectInformationConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\SQL2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa")]
        public string ProjectInformationConnectionString10 {
            get {
                return ((string)(this["ProjectInformationConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\SQL2005;Initial Catalog=ProjectInformation;Persist Secur" +
            "ity Info=True;User ID=sa;Password=sa")]
        public string ProjectInformationConnectionString11 {
            get {
                return ((string)(this["ProjectInformationConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=projectChange;Persist Security I" +
            "nfo=True;User ID=sa")]
        public string projectChangeConnectionString {
            get {
                return ((string)(this["projectChangeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=projectChange;User ID=sa")]
        public string projectChangeConnectionString1 {
            get {
                return ((string)(this["projectChangeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectQuali;Persist Security In" +
            "fo=True;User ID=sa")]
        public string ProjectQualiConnectionString {
            get {
                return ((string)(this["ProjectQualiConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=ProjectQuali;User ID=sa")]
        public string ProjectQualiConnectionString1 {
            get {
                return ((string)(this["ProjectQualiConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=projectChange;Persist Security I" +
            "nfo=True;User ID=sa;Password=sa")]
        public string projectChangeConnectionString2 {
            get {
                return ((string)(this["projectChangeConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=BaseProjectInformation;Persist S" +
            "ecurity Info=True;User ID=sa;Password=sa")]
        public string BaseProjectInformationConnectionString {
            get {
                return ((string)(this["BaseProjectInformationConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=EGBPBaseInfo;Persist Security In" +
            "fo=True;User ID=sa")]
        public string EGBPBaseInfoConnectionString {
            get {
                return ((string)(this["EGBPBaseInfoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=BaseProjectInformation;Persist S" +
            "ecurity Info=True;User ID=sa")]
        public string BaseProjectInformationConnectionString1 {
            get {
                return ((string)(this["BaseProjectInformationConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2008;Initial Catalog=EGBPBaseInfo;Persist Security In" +
            "fo=True;User ID=sa")]
        public string EGBPBaseInfoConnectionString1 {
            get {
                return ((string)(this["EGBPBaseInfoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterBJ;Persist Security Info" +
            "=True;User ID=sa;Password=sa")]
        public string dbCenterBJConnectionString {
            get {
                return ((string)(this["dbCenterBJConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbQualiBJ;Persist Security Info=" +
            "True;User ID=sa")]
        public string dbQualiBJConnectionString {
            get {
                return ((string)(this["dbQualiBJConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbQualiBJ;Persist Security Info=" +
            "True;User ID=sa")]
        public string dbQualiBJConnectionString1 {
            get {
                return ((string)(this["dbQualiBJConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterBJ;Persist Security Info" +
            "=True;User ID=sa;Password=sa")]
        public string dbCenterBJConnectionString1 {
            get {
                return ((string)(this["dbCenterBJConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbQualiBJ;User ID=sa")]
        public string dbQualiBJConnectionString2 {
            get {
                return ((string)(this["dbQualiBJConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbQualiBJ;Persist Security Info=" +
            "True;User ID=sa;Password=sa")]
        public string dbQualiBJConnectionString3 {
            get {
                return ((string)(this["dbQualiBJConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterBJ;Persist Security Info" +
            "=True;User ID=sa")]
        public string dbCenterBJConnectionString2 {
            get {
                return ((string)(this["dbCenterBJConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterNMG;User ID=sa")]
        public string dbCenterNMGConnectionString {
            get {
                return ((string)(this["dbCenterNMGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterNMG;Persist Security Inf" +
            "o=True;User ID=sa")]
        public string dbCenterNMGConnectionString1 {
            get {
                return ((string)(this["dbCenterNMGConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterKCSJ;User ID=sa")]
        public string dbCenterKCSJConnectionString {
            get {
                return ((string)(this["dbCenterKCSJConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterKCSJ;User ID=sa")]
        public string dbCenterKCSJConnectionString1 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterKCSJ;Persist Security In" +
            "fo=True;User ID=sa")]
        public string dbCenterKCSJConnectionString2 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterKCSJ;Persist Security In" +
            "fo=True;User ID=sa")]
        public string dbCenterKCSJConnectionString3 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\sql2005;Initial Catalog=dbCenterKCSJ;User ID=sa;Password" +
            "=sa")]
        public string dbCenterKCSJConnectionString4 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOTT-XKZN5MLU7D\\SQL2005;Initial Catalog=dbCenterKCSJ;Persist Security" +
            " Info=True;User ID=sa;Password=sa")]
        public string dbCenterKCSJConnectionString5 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOTT-XKZN5MLU7D\\SQL2005;Initial Catalog=dbCenterKCSJ;Persist Security" +
            " Info=True;User ID=sa;Password=sa")]
        public string dbCenterKCSJConnectionString6 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.11\\SQL2005;Initial Catalog=dbCenterKCSJ;User ID=sa;Password" +
            "=sa")]
        public string dbCenterKCSJConnectionString7 {
            get {
                return ((string)(this["dbCenterKCSJConnectionString7"]));
            }
        }
    }
}
