USE [dbCenter]
GO

/****** Object:  Table [dbo].[TC_SGXKZ_TFGTZ]    Script Date: 2015/4/12 22:15:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TC_SGXKZ_TFGTZ](
	[FId] [varchar](36) NOT NULL,
	[FAppId] [varchar](max) NULL,
	[TGPC] [varchar](36) NOT NULL,
	[ND] [int] NOT NULL,
	[TGRQ] [date] NULL,
	[FGRQ] [date] NULL,
	[TGYY] [varchar](200) NULL,
	[FBZT] [int] NOT NULL,
	[PCSL] [int] NOT NULL,
 CONSTRAINT [PK_TC_SGXKZ_TFGTZ] PRIMARY KEY CLUSTERED 
(
	[FId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TC_SGXKZ_TFGTZ] ADD  CONSTRAINT [DF_TC_SGXKZ_TFGTZ_PCSL]  DEFAULT ((0)) FOR [PCSL]
GO

