USE [dbCenter]
GO

/****** Object:  Table [dbo].[TC_BHGD_PrjItemMappingBatch]    Script Date: 2015/3/26 17:16:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TC_BHGD_PrjItemMappingBatch](
	[FId] [varchar](36) NOT NULL,
	[FBatchId] [varchar](36) NOT NULL,
	[FPrjItemId] [varchar](36) NOT NULL,
 CONSTRAINT [PK_TC_BHGD_PrjItemMappingBatch] PRIMARY KEY CLUSTERED 
(
	[FId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


