USE [dbCenter]
GO

/****** Object:  Index [NonClusteredIndex-20150518-191304]    Script Date: 2015/5/19 9:05:20 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20150518-191304] ON [dbo].[TC_PrjItem_Emp_Lock]
(
	[FAppId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


USE [dbCenter]
GO

/****** Object:  Index [NonClusteredIndex-20150518-191810]    Script Date: 2015/5/19 9:05:40 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20150518-191810] ON [dbo].[TC_PrjItem_Emp_Lock]
(
	[FPrjItemId] ASC,
	[FAppId] ASC,
	[FEmpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


USE [dbCenter]
GO

/****** Object:  Index [NonClusteredIndex-20150518-191856]    Script Date: 2015/5/19 9:06:58 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20150518-191856] ON [dbo].[TC_PrjItem_Emp]
(
	[EmpType] ASC,
	[FEntType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


USE [dbCenter]
GO

/****** Object:  Index [NonClusteredIndex-20150518-191955]    Script Date: 2015/5/19 9:07:37 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20150518-191955] ON [dbo].[TC_SGXKZ_PrjInfo]
(
	[FAppId] ASC,
	[FPrjItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


