<?xml version="1.0" encoding="utf-8"?><Database Name="JST_XZSPBaseInfo" Class="DB1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sql;Initial Catalog=JST_XZSPBaseInfo;Persist Security Info=True;User ID=jkc115" SettingsObjectName="EgovaDAO.Properties.Settings" SettingsPropertyName="JST_XZSPBaseInfoConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QY_JBXX" Member="QY_JBXX">
    <Type Name="QY_JBXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="QYMC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="QYCYM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JGDM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SSDBM" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="RegAdrProvince" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="RegAdrCity" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="RegAdrCountry" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="RegAdrProvinceName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegAdrCityName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RegAdrCountryName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZCDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ZCDZYZBM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="QYXXDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XXDZYZBM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZGBM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LSGXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LSGXMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYCLRQ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="GSZCRQ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="JJXZBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="JJXZMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="YEZZZCH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="YEZZFZJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZCZBJ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HBLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HBLXMC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KHYH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="KHYHZH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYWZ" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="DZYJ" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="CZ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LXR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LXDH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FRDB" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FRDBSJH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CYRYNMRS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JSJJRYZS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YZCRYS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GJZCRS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZJZCRS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZCRYZS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GDZC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GDZCNZJE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LDZC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FZZE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JZC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QYZSR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GCJSCB" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="GLFY" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="LSZE" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="SDS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SCSJE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LRZE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JLR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JZCSYL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ZBBZZZL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YYLR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ZCFZL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JZYZCZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JZYZJZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LDZBC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JXSBZTS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JXSBZGL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ZLAQFSSGCS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JJSS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SWRS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZSRS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="QY_JBXX_QY_BLXWQK" Member="QY_BLXWQK" ThisKey="QYBM" OtherKey="QYBM" Type="QY_BLXWQK" />
      <Association Name="QY_JBXX_QY_GCYJXX" Member="QY_GCYJXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_GCYJXX" />
      <Association Name="QY_JBXX_QY_LHXWQK" Member="QY_LHXWQK" ThisKey="QYBM" OtherKey="QYBM" Type="QY_LHXWQK" />
      <Association Name="QY_JBXX_QY_QYBGQK" Member="QY_QYBGQK" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYBGQK" />
      <Association Name="QY_JBXX_QY_QYCYRYXX" Member="QY_QYCYRYXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYCYRYXX" />
      <Association Name="QY_JBXX_QY_QYCZRGDXX" Member="QY_QYCZRGDXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYCZRGDXX" />
      <Association Name="QY_JBXX_QY_QYHBCZXX" Member="QY_QYHBCZXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYHBCZXX" />
      <Association Name="QY_JBXX_QY_QYJL" Member="QY_QYJL" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYJL" />
      <Association Name="QY_JBXX_QY_QYLSSQXX" Member="QY_QYLSSQXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYLSSQXX" />
      <Association Name="QY_JBXX_QY_QYNJQK" Member="QY_QYNJQK" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYNJQK" />
      <Association Name="QY_JBXX_QY_QYXYPD" Member="QY_QYXYPD" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYXYPD" />
      <Association Name="QY_JBXX_QY_QYZYRYXX" Member="QY_QYZYRYXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYZYRYXX" />
      <Association Name="QY_JBXX_QY_ZYJQSB" Member="QY_ZYJQSB" ThisKey="QYBM" OtherKey="QYBM" Type="QY_ZYJQSB" />
      <Association Name="QY_JBXX_QY_QYZSXX" Member="QY_QYZSXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_QYZSXX" />
    </Type>
  </Table>
  <Table Name="dbo.QY_BLXWQK" Member="QY_BLXWQK">
    <Type Name="QY_BLXWQK">
      <Column Name="BLXWID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="WH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WJBT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BLXWFSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CFSS" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="CFYJ" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CFJL" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CFJG" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="KFZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SXRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZZRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_BLXWQK" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_GCYJXX" Member="QY_GCYJXX">
    <Type Name="QY_GCYJXX">
      <Column Name="GCYJID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="JSDW" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="JSDD" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HTJ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JSJG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XMGM" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XMFZR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="JSZB" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="XMJJ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="XMLB" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="XMCBFS" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="SGZZFS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KGRQ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="JGRQ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="JHGQ" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SJGQ" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="YWYY" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ZLPD" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AQPJ" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="HJQK" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SGDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="KCDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SJDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JLDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DLJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="YSDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZBBABH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_GCYJXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_LHXWQK" Member="QY_LHXWQK">
    <Type Name="QY_LHXWQK">
      <Column Name="LHXWID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="LHXWMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="WSBH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="WSMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="JXLB" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HJRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RYNR" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="JFZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZFZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BJDW" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HJJS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="QY_JBXX_QY_LHXWQK" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYBGQK" Member="QY_QYBGQK">
    <Type Name="QY_QYBGQK">
      <Column Name="QYBGID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BGRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BGNR" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SPBM" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_QYBGQK" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYCYRYXX" Member="QY_QYCYRYXX">
    <Type Name="QY_QYCYRYXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RYLBBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RYLBMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="ZJLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZJLXMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZJBH" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ZW" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZCBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LXDH" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SJHM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="XLBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DZYX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZGXL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SXZY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BYSJ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="BYXX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XCSZY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CYZK" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RYZKBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RYZKMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SFGMSB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZPURL" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ZCLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZCLXMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZCZYMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZGZSH" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ZCZSH" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ZCDJBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZCDJMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZCZSFZSJ" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZCZSYXQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="QY_JBXX_QY_QYCYRYXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYCZRGDXX" Member="QY_QYCZRGDXX">
    <Type Name="QY_QYCZRGDXX">
      <Column Name="CZID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CZFLXBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CZFLXMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CZFMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CZE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HBLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HBLXMC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CZBL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZJLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZJLXMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJBH" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="ZCZSH" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ZYZG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="QY_JBXX_QY_QYCZRGDXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYHBCZXX" Member="QY_QYHBCZXX">
    <Type Name="QY_QYHBCZXX">
      <Column Name="QYHBID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HBCZHQYJGDM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HBCZHQYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HBCZHQYMC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HBCZHQYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HBCZHQYLX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HBCZHQYZXZZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HBCZHQYFR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HBCZHQYFRSJG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HBCZLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HBCZSJ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="HBCZHQYZZCJE" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="HBCZPZSJ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="HBCZPZDW" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="备注" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_QYHBCZXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYJL" Member="QY_QYJL">
    <Type Name="QY_QYJL">
      <Column Name="QYJLID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYJJ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="QYZC" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="QYZZJGT" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_QYJL" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYLSSQXX" Member="QY_QYLSSQXX">
    <Type Name="QY_QYLSSQXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYLSID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYLXBM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="QYLXMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZZXL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZZLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZZDJ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SFXZZZ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XZSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SFZXZZ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ZXBH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZXMC" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FLBH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SFZDZZ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SPBM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SPSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BFSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SFZF" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_QYLSSQXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYNJQK" Member="QY_QYNJQK">
    <Type Name="QY_QYNJQK">
      <Column Name="QYNJID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ND" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="NJSJ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="NJJG" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NJBM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_QYNJQK" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYXYPD" Member="QY_QYXYPD">
    <Type Name="QY_QYXYPD">
      <Column Name="QYXYID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PDND" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="XYFZ" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="XYDJ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XYPJJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PJJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PJRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="QY_JBXX_QY_QYXYPD" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYZYRYXX" Member="QY_QYZYRYXX">
    <Type Name="QY_QYZYRYXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RYLBBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RYLBMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="ZJLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZJLXMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZJBH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZW" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZCBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LXDH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SJHM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LXDZ" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="YXBM" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="XLBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZGXL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SXZY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BYSJ" Type="System.String" DbType="VarChar(19)" CanBeNull="true" />
      <Column Name="BYXX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XCSZY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="GLZL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZPURL" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_QYZYRYXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYZZXX" Member="QY_QYZZXX">
    <Type Name="QY_QYZZXX">
      <Column Name="QYZZID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FCertiId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZSBH" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ZZLB" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ZZLBBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZZMC" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ZZMCBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZZZX" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ZZZXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZZDJ" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="ZZDJBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PZRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PZJG" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CBFW" Type="System.String" DbType="NVarChar(3000)" CanBeNull="true" />
      <Column Name="SFZD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SFZX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="QY_QYZSXX_QY_QYZZXX" Member="QY_QYZSXX" ThisKey="FCertiId" OtherKey="QYZSID" Type="QY_QYZSXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_ZYJQSB" Member="QY_ZYJQSB">
    <Type Name="QY_ZYJQSB">
      <Column Name="JQSBID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SBMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SBXH" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="SBLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZYXNZB" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="GL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YZ" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="JZ" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="SFSZYSB" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ZT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="QY_JBXX_QY_ZYJQSB" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_DBGCYJ" Member="RY_DBGCYJ">
    <Type Name="RY_DBGCYJ">
      <Column Name="RYDBGCID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZW" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RZKSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RZJSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XMZD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="JSDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HTJ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JSJG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ZLPD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="XMGM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="XMFZR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JSZB" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="XMJJ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XMLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMCBFS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SGZZFS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KGRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JGRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JHGQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SJGQ" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="YWYY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AQPJ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HJQK" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SGDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="KCDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SJDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JLDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DLJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="YSDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_DBGCYJ" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_GZDWQK" Member="RY_GZDWQK">
    <Type Name="RY_GZDWQK">
      <Column Name="RYGZDWID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYLX" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="QYCYM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JJXZ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LSGX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZGBM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZCDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ZCDZYZBM" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="QYXXDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="QYXXDZYZBM" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="LXDH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CZ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DZYJ" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="QYWZ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JLSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="YYZZZCH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FZJG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FRDB" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FRDBSJH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="YWLX" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="QYZT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_GZDWQK" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_JXJYQK" Member="RY_JXJYQK">
    <Type Name="RY_JXJYQK">
      <Column Name="RYJXJYID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PXBJM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PXKSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PXJSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PXJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="XXNR" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DD" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="KCXZ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XXXS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BXXS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CJ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HGZSH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_JXJYQK" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_KYFMCG" Member="RY_KYFMCG">
    <Type Name="RY_KYFMCG">
      <Column Name="RYKYCGID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYXM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KYCGMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CGLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZYZY" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="JYSM" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SBSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PZSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PZDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_KYFMCG" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_RYBLXWXX" Member="RY_RYBLXWXX">
    <Type Name="RY_RYBLXWXX">
      <Column Name="RYBLXWID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JSDW" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYMC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYLX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="XMDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CFRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RDDW" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BT" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NR" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="XWSS" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CFJD" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="KFZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SYFS" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SSJD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZRZTLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LJJLCS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QT" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CFWJ" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SFSD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SDLX" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SDJSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SDKSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_RYBLXWXX" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_RYJBXX" Member="RY_RYJBXX">
    <Type Name="RY_RYJBXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MZ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZZ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZW" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BYYX" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="BYSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SXZY" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="LXDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="YXBM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DZYX" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BGDH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="GRDH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZPURL" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="RYZT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QDZCSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_DBGCYJ" Member="RY_DBGCYJ" ThisKey="RYBH" OtherKey="RYBH" Type="RY_DBGCYJ" />
      <Association Name="RY_RYJBXX_RY_GZDWQK" Member="RY_GZDWQK" ThisKey="RYBH" OtherKey="RYBH" Type="RY_GZDWQK" />
      <Association Name="RY_RYJBXX_RY_JXJYQK" Member="RY_JXJYQK" ThisKey="RYBH" OtherKey="RYBH" Type="RY_JXJYQK" />
      <Association Name="RY_RYJBXX_RY_KYFMCG" Member="RY_KYFMCG" ThisKey="RYBH" OtherKey="RYBH" Type="RY_KYFMCG" />
      <Association Name="RY_RYJBXX_RY_RYBLXWXX" Member="RY_RYBLXWXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYBLXWXX" />
      <Association Name="RY_RYJBXX_RY_RYXYPD" Member="RY_RYXYPD" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYXYPD" />
      <Association Name="RY_RYJBXX_RY_RYYLXWXX" Member="RY_RYYLXWXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYYLXWXX" />
      <Association Name="RY_RYJBXX_RY_RYZSXX" Member="RY_RYZSXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYZSXX" />
      <Association Name="RY_RYJBXX_RY_ZJGCXM" Member="RY_ZJGCXM" ThisKey="RYBH" OtherKey="RYBH" Type="RY_ZJGCXM" />
    </Type>
  </Table>
  <Table Name="dbo.RY_RYXYPD" Member="RY_RYXYPD">
    <Type Name="RY_RYXYPD">
      <Column Name="RYXXPDID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSLX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZSJB" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZSBH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZCZY" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PDND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XYFZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XYDJ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_RYXYPD" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_RYYLXWXX" Member="RY_RYYLXWXX">
    <Type Name="RY_RYYLXWXX">
      <Column Name="RYYLXWID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="RYLX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="WSBH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HJLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JXJB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYNR" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RDRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BFJG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JFZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ZFZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RDJG" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XWMC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="QT" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QYDQ" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_RYYLXWXX" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_RYZSXX" Member="RY_RYZSXX">
    <Type Name="RY_RYZSXX">
      <Column Name="RYZSXXID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="XB" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ZW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JSZC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="QDZCSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSLX" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="ZSJB" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZCZSBH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZGZSH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZCZSH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="YZH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZCZY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZSYXQKSSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZSYXQJSSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FZSJ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FZJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZSZT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SFDY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_RYZSXX" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RY_ZJGCXM" Member="RY_ZJGCXM">
    <Type Name="RY_ZJGCXM">
      <Column Name="RYZJGCID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QYSD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RYBH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZJLX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SFZH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZW" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RZKSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XMBM" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="XMMC" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="XMZD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMDZ" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="JSDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="HTJ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="XMGM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMFZR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JSZB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMJJ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="XMLB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="XMCBFS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SGZZFS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KGRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JGRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JHGQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SGDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="KCDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SJDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="JLDW" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DLJG" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BZ" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="RY_RYJBXX_RY_ZJGCXM" Member="RY_RYJBXX" ThisKey="RYBH" OtherKey="RYBH" Type="RY_RYJBXX" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_QY_ZZXX" Member="V_QY_ZZXX">
    <Type Name="V_QY_ZZXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="zsbh" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="zz" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_QY_ZXZZXX" Member="V_QY_ZXZZXX">
    <Type Name="V_QY_ZXZZXX">
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="zsbh" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="zz" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QY_QYZSXX" Member="QY_QYZSXX">
    <Type Name="QY_QYZSXX">
      <Column Name="QYZSID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QYBM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZSLXBM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ZSLXMC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ZSBH" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="ZSDJMC" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="YXKSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="YXJSRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZBSL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FBSL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZSZJFBSL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZSBBFBSL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SFYX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BFBM" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="BFBMBH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BFRQ" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SFZD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QY_QYZSXX_QY_QYZZXX" Member="QY_QYZZXX" ThisKey="QYZSID" OtherKey="FCertiId" Type="QY_QYZZXX" />
      <Association Name="QY_JBXX_QY_QYZSXX" Member="QY_JBXX" ThisKey="QYBM" OtherKey="QYBM" Type="QY_JBXX" IsForeignKey="true" />
    </Type>
  </Table>
</Database>